imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    log_files_directory: '%kernel.root_dir%/../media/logFiles'
    overlay_directory: '%kernel.root_dir%/../media/overlay'
    log_support_directory: '%kernel.root_dir%/../media/log_support'
    #ups_status_key: '%ups_status_key%'
    #people_count_key: '%people_count_key%'
    #dark_sky_key: '%dark_sky_key%'

framework:
    #esi:             ~
    #
    translator:      { fallbacks: ["%locale%"] }
    #translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        cookie_lifetime: 21600
        gc_maxlifetime: 21600
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
    globals:
        gmapsKey: "%gmaps_apikey%"
        weatherUser: "%raintoday_username%"
        weatherPass: "%raintoday_password%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#KNP Snappy
knp_snappy:  
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:
            - { name: 'viewport-size', value: ‘1024x768’ }
            - { name: 'page-size', value: 'A4' }
            - { name: 'header-left', value: 'Confidential Information' }
            - { name: 'header-right', value: 'Event Control' }
            - { name: 'header-line', value: true }
            - { name: 'footer-center', value: '[page]/[topage]' }
            - { name: 'footer-line', value: true }
            - { name: 'enable-javascript', value: true }
            - { name: 'no-stop-slow-scripts', value: true }
            - { name: 'javascript-delay', value: '5000' }
            - { name: 'debug-javascript', value: true }
            
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

vich_uploader:
    db_driver: orm
    
    mappings:
        event_overlay:
            uri_prefix:         /overlay
            upload_destination: '%kernel.root_dir%/../media/overlay'
            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            
        log_support_file:
            uri_prefix:         /log_support
            upload_destination: '%kernel.root_dir%/../media/log_support'
            
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            
            namer:              vich_uploader.namer_uniqid
    
xiidea_easy_audit:
    entity_class : AppBundle\Entity\AuditLog
    
    #user property to use as actor of an event
    #valid value will be any valid property of your user class
    user_property : ~ # or username                            

    #List of doctrine entity:event you wish to track or set to false to disable logs for doctrine events
    # valid events are = [created, updated, deleted]
    doctrine_entities :                                              
         AppBundle\Entity\log_entries: ~
         AppBundle\Entity\event: ~
         AppBundle\Entity\general_log: ~
         AppBundle\Entity\medical_log: ~
         AppBundle\Entity\security_log: ~
         AppBundle\Entity\lost_property: ~
         AppBundle\Entity\event_control_register: ~
         AppBundle\Entity\User: ~
         AppBundle\Entity\UPS: ~

    #List all events you want to track  (Optional from v1.2.1 you can now use subscriber to define it)
    events :                                                   #Optional
        - security.interactive_login
        - security.authentication.failure

    #List all custom resolver for event
    #custom_resolvers :
    #       security.interactive_login : user.event_resolver
    #       security.authentication.failure : user.event_resolver

    #logger_channel:
    #    xiidea.easy_audit.logger.service: ["info", "debug"]
    #    file.logger: ["!info", "!debug"]

    #Custom Event Resolver Service

d_zunke_slack:
    token: "%echo-charlie%"
    identities:
        echo-charlie:
            icon_emoji:    :rotating_light:
