_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
app:
    resource: "@AppBundle/ControlRoomLog/"
    type:     annotation
  
logout:
    path: /logout

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /
