# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: 
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_USER:      ROLE_VIEW
        #ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            #logout:       true
            #anonymous:    true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/camera/newdata/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/update/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/LED/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/status/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/so/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: ROLE_USER, requires_channel: https }
        - { path: ^/fireregister, role: ROLE_USER, requires_channel: https }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/user/*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/event, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/event/weather/radar, roles: ROLE_VIEW, requires_channel: http }
        - { path: ^/event/*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/$, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/*, roles: ROLE_VIEW, requires_channel: https }
