# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: 
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_USER:      ROLE_VIEW
        ROLE_FIELD:      ROLE_VIEW
        #ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
                
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            #        - app.api_token_authenticator
            #    entry_point: app.form_login_authenticator
            #logout:       true
            #anonymous:    true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/peoplecounting/slack_occupancy/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/camera_count/newdata/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/venue/event/*, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/firebase/register/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/venue/skew/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/update/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/json/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/LED/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/UPS/status/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/so/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: ROLE_USER, requires_channel: https }
        - { path: ^/mySettings/, role: ROLE_USER, requires_channel: https }
        - { path: ^/fireregister, role: ROLE_USER, requires_channel: https }
        - { path: ^/Alert/*, roles: ROLE_VIEW, requires_channel: https }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/fieldUser, roles: ROLE_USER, requires_channel: https }
        - { path: ^/user/setEvent/*, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/user/setEvent, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/user/, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/user, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/user/*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/audit, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/event/weather/radar, roles: ROLE_VIEW }
        - { path: ^/event/weather/, roles: ROLE_VIEW }
        - { path: ^/map/*, roles: ROLE_VIEW }
        - { path: ^/map, roles: ROLE_VIEW }
        - { path: ^/mapjsondata, roles: ROLE_VIEW }
        - { path: ^/mapjsondata/*, roles: ROLE_VIEW }
        - { path: ^/event, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/event/edit/*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/event/delete/*, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/event/new/, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/log/*, roles: ROLE_VIEW }
        - { path: ^/log, roles: ROLE_VIEW }
        - { path: ^/table/*, roles: ROLE_VIEW }
        - { path: ^/table, roles: ROLE_VIEW }
        - { path: ^/, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/$, roles: ROLE_VIEW, requires_channel: https }
        - { path: ^/*, roles: ROLE_VIEW, requires_channel: https }
