# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    doctrine.alert_listener:
        class: AppBundle\Entity\AlertListener
        arguments: [d_zunke_slack.config]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#app.slugger:
 #   class: AppBundle\Utils\Slugger
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@doctrine', '@security.token_storage']

        tags:
            - { name: twig.extension }

