# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
        
#    app.api_token_authenticator:
#        class: AppBundle\Security\ApiTokenAuthenticator
#        arguments: ["@doctrine.orm.entity_manager"]
        
    doctrine.alert_listener:
        class: AppBundle\Entity\AlertListener
        arguments: ['@dz.slack.client', '@dz.slack.identity_bag', '@service_container']
        tags:
           - { name: doctrine.event_listener, event: prePersist }
           - { name: doctrine.event_listener, event: postPersist }
           
    doctrine.log_listener:
        class: AppBundle\Entity\LogListener
        arguments: ['@dz.slack.client', '@dz.slack.identity_bag', '@service_container']
        tags:
           - { name: doctrine.event_listener, event: postPersist }
           - { name: doctrine.event_listener, event: postUpdate }
           
    doctrine.camera_count_listener:
        class: AppBundle\Entity\CameraCountListener
        arguments: ['@dz.slack.client', '@dz.slack.identity_bag', '@service_container']
        tags:
           - { name: doctrine.event_listener, event: postPersist }
           
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#app.slugger:
 #   class: AppBundle\Utils\Slugger
    
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@doctrine', '@security.token_storage']

        tags:
            - { name: twig.extension }

